[agenda]
nome = "Agenda"
painel_glob = "PAINEL DE AGENDAMENTOS (BOIODATA) - SOLB*.xlsx"
nome_saida = "PAINEL DE AGENDAMENTOS (BOIODATA) - SOLB - 2025 ATÉ {mes} {ano}.xlsx"
pasta_painel = "atualizados"
pasta_entrada = "dados/entrada/agenda"
pasta_saida = "dados/saida"
aba_brutos = "INPUT"
aba_tratados = "INPUT"
tabela_brutos = "_9aacsokpj"
tabela_tratados = "_9aacsokpj"

[exames]
nome = "Exames"
painel_glob = "PAINEL DE EXAMES (BIODATA) - SOLB*.xlsx"
nome_saida = "PAINEL DE EXAMES (BIODATA) - SOLB - 2025 ATÉ {mes} {ano}.xlsx"
pasta_painel = "atualizados"
pasta_entrada = "dados/entrada/exames"
pasta_saida = "dados/saida"
aba_brutos = "DADOS BRUTOS"
aba_tratados = "DADOS TRATADOS"
tabela_brutos = "Tabela1"
tabela_tratados = "exames_tratados"

[cirurgias]
nome = "Cirurgias"
painel_glob = "PAINEL DE CIRURGIAS (BIODATA) - SOLB*.xlsx"
nome_saida = "PAINEL DE CIRURGIAS (BIODATA) - SOLB - 2025 ATÉ {mes} {ano}.xlsx"
pasta_painel = "atualizados"
pasta_entrada = "dados/entrada/cirurgias"
pasta_saida = "dados/saida"
aba_brutos = "DADOS BRUTOS"
aba_tratados = "DADOS TRATADOS"
tabela_brutos = "Tabela1"
tabela_tratados = "cirurgias_tratado"
aba_auxiliar = "INPUTS"
tabela_auxiliar = "Tabela7"
coluna_mes_auxiliar = "Mês"
coluna_quantidade_auxiliar = "QTD"

[atendimentos]
nome = "Atendimentos"
painel_glob = "PAINEL DE ATENDIMENTOS (BIODATA) - SOLB*.xlsx"
nome_saida = "PAINEL DE ATENDIMENTOS (BIODATA) - SOLB - 2025 ATÉ {mes} {ano}.xlsx"
pasta_painel = "atualizados"
pasta_entrada = "dados/entrada/atendimentos"
pasta_saida = "dados/saida"
aba_brutos = "DADOS BRUTOS"
aba_tratados = "DADOS TRATADOS"
tabela_brutos = "Tabela2"
tabela_tratados = "Tabela1"

[comparativo]
nome = "Comparativo"
painel_glob = "PAINEL COMPARATIVO (BIODATA) - SOLB*.xlsx"
nome_saida = "PAINEL COMPARATIVO (BIODATA) - SOLB - 2025 ATÉ {mes} {ano}.xlsx"
pasta_painel = "atualizados"
pasta_entrada = "dados/entrada/comparativo"
pasta_saida = "dados/saida"
aba_brutos = "TRATADO"
aba_tratados = "TRATADO"
tabela_brutos = "Tabela1"
tabela_tratados = "Tabela1"

[3cx]
nome = "3CX"
painel_glob = "PAINEL LIGAÇÕES (3CX) - SOLB*.xlsx"
nome_saida = "PAINEL LIGAÇÕES (3CX) - SOLB - 2022 ATÉ {mes} {ano}.xlsx"
pasta_painel = "atualizados"
pasta_entrada = "dados/entrada/3cx"
pasta_saida = "dados/saida"
aba_brutos = "CONFIG - 2025"
aba_tratados = "CONFIG - 2025"
tabela_brutos = "Tabela1"
tabela_tratados = "Tabela2"
